services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile # Chỉ định Dockerfile mới
    container_name: tutor_system_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SPRING_PROFILES_ACTIVE: docker
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"  # Host port : Container port
    volumes:
      - db_data:/var/lib/mysql
      - ./docker:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tutor_net

  api:
    build: .
    container_name: tutor_system_api
    restart: unless-stopped
    environment:
      # Sử dụng biến từ .env
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: ${SERVER_PORT}
      APP_JWT_SECRET: ${JWT_SECRET} # Cần sửa thêm trong application.yml để nhận biến này
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    command: [ "java", "-jar", "/app/app.jar" ]
    networks:
      - tutor_net

volumes:
  db_data:

networks:
  tutor_net:
    driver: bridge