services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile # Chỉ định Dockerfile mới
    container_name: tutor_system_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tutor_system
      SPRING_PROFILES_ACTIVE: docker
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3307:3306"  # Host port : Container port
    volumes:
      - db_data:/var/lib/mysql
      - ./docker:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tutor_net

  api:
    build: .
    container_name: tutor_system_api
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tutor_system?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&useUnicode=UTF-8&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8081
      SERVER_ADDRESS: 0.0.0.0
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    command: ["java", "-jar", "/app/app.jar"]  # <-- thay cho entrypoint.sh
    networks:
      - tutor_net


volumes:
  db_data:

networks:
  tutor_net:
    driver: bridge